name: WonderHuman
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10.13
  - pip=23.3.1
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - tqdm
  - tensorboard
  - scipy
  - pip:
    - opencv-python